//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursos
    {
        public int id_curso { get; set; }
        public int id_materia { get; set; }
        public int id_comision { get; set; }
        public int anio_calendario { get; set; }
        public int cupo { get; set; }
    
        public virtual comisiones comisiones { get; set; }
        public virtual materias materias { get; set; }
    }
}
