USE [master]
GO

/****** Object:  Database [tp2_net]    Script Date: 11/8/2020 21:04:35 ******/
CREATE DATABASE [tp2_net]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tp2_net', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tp2_net.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'tp2_net_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tp2_net_log.ldf' , SIZE = 5184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tp2_net].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tp2_net] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tp2_net] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tp2_net] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tp2_net] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tp2_net] SET ARITHABORT OFF 
GO

ALTER DATABASE [tp2_net] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tp2_net] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tp2_net] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tp2_net] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tp2_net] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tp2_net] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tp2_net] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tp2_net] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tp2_net] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tp2_net] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tp2_net] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tp2_net] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tp2_net] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tp2_net] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tp2_net] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tp2_net] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tp2_net] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tp2_net] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tp2_net] SET  MULTI_USER 
GO

ALTER DATABASE [tp2_net] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tp2_net] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tp2_net] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tp2_net] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tp2_net] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tp2_net] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tp2_net] SET  READ_WRITE 
GO

